USE DataBaseEG_18373579

--（1）
SELECT 学号=SNO, 姓名=SNAME, 性别=SSEX, 生日=SBIRTHDAY, 班级=CLASS
	FROM STUDENT
	ORDER BY SNO DESC

--（2）
SELECT 学号=SNO, 姓名=SNAME, 班级=CLASS
	FROM STUDENT
	WHERE SNAME LIKE '___'
	ORDER BY CLASS ASC, SNO DESC

--（3）
SELECT *
	FROM STUDENT
	WHERE SSEX='男' AND SNO>105
	ORDER BY SNO

--（4）
SELECT 课程数量=COUNT(CNAME)
	FROM COURSE

--（5）
SELECT 课程编号=SCORE.CNO, 课程名称=CNAME, 平均分=AVG(DEGREE)
	FROM SCORE, COURSE
	WHERE SCORE.CNO = COURSE.CNO
	GROUP BY SCORE.CNO, CNAME
	ORDER BY AVG(DEGREE) DESC

--（6）
SELECT 学号=SCORE.SNO, 姓名=SNAME, 班级=CLASS, 平均分=AVG(DEGREE)
	FROM STUDENT, SCORE
	WHERE STUDENT.SNO = SCORE.SNO
	GROUP BY SCORE.SNO, SNAME, CLASS
	HAVING AVG(DEGREE) BETWEEN 80 AND 100
	ORDER BY AVG(DEGREE) DESC
