--´´½¨±í

use DataBaseEG_18373579

CREATE TABLE STUDENT
(
	SNO VARCHAR(3) NOT NULL,
	SNAME VARCHAR(8) NOT NULL,
	SSEX VARCHAR(2) NOT NULL,
	SBIRTHDAY DATETIME,
	CLASS VARCHAR(6),
	CONSTRAINT PK_student PRIMARY KEY (SNO)
)
GO

CREATE TABLE COURSE
(
	CNO VARCHAR(5) NOT NULL,
	CNAME VARCHAR(20) NOT NULL,
	CONSTRAINT PK_course PRIMARY KEY (CNO)
)
GO

CREATE TABLE SCORE
(
	SNO VARCHAR(3) NOT NULL,
	CNO VARCHAR(5) NOT NULL,
	DEGREE NUMERIC(10, 1) NOT NULL
)
GO

ALTER TABLE SCORE
ADD CONSTRAINT FK_SCORE_STUDENT
FOREIGN KEY(SNO) REFERENCES STUDENT(SNO)

ALTER TABLE SCORE
ADD CONSTRAINT FK_SCORE_COURSE
FOREIGN KEY(CNO) REFERENCES COURSE(CNO)